apiVersion: v1
kind: Service
metadata:
  name: darkologija-service
  spec:
    type: LoadBalancer
    selector:
      owner: darko
    ports:
      - protocol: TCP
      port: 8080
      targetPort: 8080